###############################################################
# monolit-planner-api — triggered only on changes in Monolit-Planner/**
###############################################################
substitutions:
  _REGION: europe-west3

steps:
  - name: gcr.io/cloud-builders/docker
    id: build-monolit
    args:
      - build
      - -f
      - Monolit-Planner/Dockerfile
      - -t
      - gcr.io/$PROJECT_ID/monolit-planner-api:$SHORT_SHA
      - -t
      - gcr.io/$PROJECT_ID/monolit-planner-api:latest
      - Monolit-Planner

  - name: gcr.io/cloud-builders/docker
    id: push-monolit
    waitFor: [build-monolit]
    args: [push, gcr.io/$PROJECT_ID/monolit-planner-api, --all-tags]

  - name: gcr.io/cloud-builders/gcloud
    id: deploy-monolit
    waitFor: [push-monolit]
    args:
      - run
      - deploy
      - monolit-planner-api
      - --image=gcr.io/$PROJECT_ID/monolit-planner-api:$SHORT_SHA
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated

images:
  - gcr.io/$PROJECT_ID/monolit-planner-api:$SHORT_SHA

timeout: 600s
options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
