services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/"]
      interval: 10s
      timeout: 3s
      retries: 10
    # depends_on можно включить, когда реально используем внешние сервисы
    # depends_on:
    #   db: { condition: service_healthy }
    #   redis: { condition: service_started }
    #   minio: { condition: service_healthy }

  db:
    image: postgres:16
    profiles: [ "full" ]
    environment:
      POSTGRES_DB: stavagent
      POSTGRES_USER: stav
      POSTGRES_PASSWORD: stavpass
    ports:
      - "5432:5432"   # для локальной отладки; в CI не обязательно
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stav -d stavagent"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    profiles: [ "full" ]
    ports: [ "6379:6379" ]

  minio:
    image: minio/minio
    profiles: [ "full" ]
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
  miniodata:
