name: urs-deploy
github:
  owner: alpro1000
  name: STAVAGENT
  push:
    branch: "^main$"
filename: cloudbuild-urs.yaml
includedFiles:
  - "URS_MATCHER_SERVICE/**"
substitutions:
  _REGION: europe-west3
  _TAG: $SHORT_SHA
