#!/usr/bin/env bash
# gcs_sort.sh — Sort gs://stavagent-cenik-norms/ into B3/B5/B6/B7 layout.
#
# Generated by STAVAGENT session (branch claude/gcs-bucket-sort-pointers-CYaYp)
# from the file list captured 2026-04-27. Each phase is gated by a y/N
# prompt — read the output before continuing.
#
# Phases:
#   A  preflight  — verify gsutil + bucket access, count files, diff list
#   B  hash audit — CRC32C across all 64 files; halt if extra duplicates appear
#   C  moves      — 63 unique files into slug folders (source*.pdf naming)
#   D  duplicate  — archive 46324_Archive.pdf -> _archive/duplicates/
#   E  index      — upload scripts/INDEX.json to gs://.../_index/INDEX.json
#
# Re-running is safe: gsutil mv is idempotent (already-moved files just fail
# fast). To redo from scratch, restore objects from the bucket's versioning
# history first.
set -uo pipefail

BUCKET="gs://stavagent-cenik-norms"
ARCHIVE_BUCKET="${BUCKET}/_archive/duplicates"
INDEX_PATH="${BUCKET}/_index/INDEX.json"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
INDEX_FILE="${SCRIPT_DIR}/INDEX.json"

# Pre-confirmed duplicate (per task spec): keep PROJEKT...D1-150, drop 46324_Archive.
EXPECTED_DUPLICATE_GROUPS=1

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
gate() {
  local phase="$1"
  echo
  echo "═══════════════════════════════════════════════════════════════════"
  echo "  $phase"
  echo "═══════════════════════════════════════════════════════════════════"
  read -r -p "Continue with this phase? [y/N] " ans
  case "$ans" in
    y|Y|yes|YES) return 0 ;;
    *)           echo "Aborted at $phase."; exit 0 ;;
  esac
}

mv_one() {
  # mv_one <src_filename> <dest_path_relative_to_bucket>
  local src="$1" dst="$2"
  local src_url="${BUCKET}/${src}"
  local dst_url="${BUCKET}/${dst}"
  echo "→ ${src}"
  echo "  ${dst}"
  if ! gsutil mv "$src_url" "$dst_url"; then
    echo "    ✗ FAILED — investigate before continuing." >&2
    return 1
  fi
}

# ---------------------------------------------------------------------------
# Phase A — preflight
# ---------------------------------------------------------------------------
gate "PHASE A — preflight"

if ! command -v gsutil >/dev/null 2>&1; then
  echo "ERROR: gsutil not found in PATH. Install Google Cloud SDK first." >&2
  exit 1
fi

echo "Bucket listing (top-level objects):"
if ! gsutil ls "${BUCKET}/" > /tmp/gcs_sort_listing.txt; then
  echo "ERROR: cannot list ${BUCKET}/. Check auth (gcloud auth login)." >&2
  exit 1
fi
top_count=$(grep -c '\.pdf$' /tmp/gcs_sort_listing.txt || true)
echo "  PDFs at bucket root: ${top_count}"
echo "  (expected 64 on first run, 0 after a successful sort)"

# ---------------------------------------------------------------------------
# Phase B — hash audit (CRC32C — GCS native, ~free)
# ---------------------------------------------------------------------------
gate "PHASE B — hash audit (CRC32C)"

echo "Computing CRC32C across all bucket objects (this can take ~1 min)..."
> /tmp/gcs_sort_hashes.txt
gsutil ls -L "${BUCKET}/**" 2>/dev/null \
  | awk '
    /^gs:/ { url=$1; next }
    /Hash \(crc32c\)/ { gsub(/.*: /, ""); gsub(/ +$/, ""); print $0 " " url }
  ' > /tmp/gcs_sort_hashes.txt

dup_groups=$(awk '{print $1}' /tmp/gcs_sort_hashes.txt \
              | sort | uniq -c | awk '$1>1' | wc -l)
echo "  Duplicate hash groups found: ${dup_groups}"
echo "  Expected (pre-confirmed):    ${EXPECTED_DUPLICATE_GROUPS}"

if [ "${dup_groups}" -gt "${EXPECTED_DUPLICATE_GROUPS}" ]; then
  echo
  echo "✗ More duplicate groups than expected. Listing all groups:"
  awk '{print $1}' /tmp/gcs_sort_hashes.txt | sort | uniq -c | awk '$1>1' \
    | while read -r count hash; do
        echo "  hash=${hash}  count=${count}"
        grep "^${hash} " /tmp/gcs_sort_hashes.txt | awk '{print "    "$2}'
      done
  echo
  echo "STOP. Resolve these groups with the developer before re-running this script." >&2
  exit 2
fi

if [ "${dup_groups}" -eq 1 ]; then
  echo "  ✓ Only the pre-confirmed duplicate group is present."
fi

# ---------------------------------------------------------------------------
# Phase C — moves (63 unique files)
# ---------------------------------------------------------------------------
gate "PHASE C — moves (63 unique files)"

# B3_current_prices (3)
mv_one "Cenová nabídka - BERGER BOHEMIA - Modernizace trati Plzeň-Chotěšov - aktual..pdf" \
       "B3_current_prices/projekt_berger_bohemia_modernizace_trati_plzen_chotesov/source.pdf"
mv_one "Ceník Transportbeton a značkové produkty betonárna Plzeň 2026.pdf" \
       "B3_current_prices/transportbeton_plzen_betonarna_2026/source.pdf"
mv_one "Ceník čerpání betonárna Plzeň 2026.pdf" \
       "B3_current_prices/cerpani_plzen_betonarna_2026/source.pdf"

# B5_tech_cards — PERI vendor manuals (43 files / 26 slugs)
mv_one "domino-návod.pdf"       "B5_tech_cards/peri_domino_panel_formwork/source_navod.pdf"
mv_one "domino-prospekt.pdf"    "B5_tech_cards/peri_domino_panel_formwork/source_prospekt.pdf"
mv_one "domino-plakát.pdf"      "B5_tech_cards/peri_domino_panel_formwork/source_plakat.pdf"

mv_one "duo-návod.pdf"          "B5_tech_cards/peri_duo_lightweight_formwork/source_navod.pdf"
mv_one "duo-prospekt.pdf"       "B5_tech_cards/peri_duo_lightweight_formwork/source_prospekt.pdf"
mv_one "duo-plakát.pdf"         "B5_tech_cards/peri_duo_lightweight_formwork/source_plakat.pdf"

mv_one "maximo-návod.pdf"       "B5_tech_cards/peri_maximo_wall_formwork/source_navod.pdf"
mv_one "maximo-prospekt.pdf"    "B5_tech_cards/peri_maximo_wall_formwork/source_prospekt.pdf"
mv_one "maximo-plakát.pdf"      "B5_tech_cards/peri_maximo_wall_formwork/source_plakat.pdf"

mv_one "maximo-mxk-návod.pdf"    "B5_tech_cards/peri_maximo_mxk_column_formwork/source_navod.pdf"
mv_one "maximo-mxk-prospekt.pdf" "B5_tech_cards/peri_maximo_mxk_column_formwork/source_prospekt.pdf"

mv_one "multiflex-návod.pdf"    "B5_tech_cards/peri_multiflex_slab_formwork/source_navod.pdf"
mv_one "multiflex-prospekt.pdf" "B5_tech_cards/peri_multiflex_slab_formwork/source_prospekt.pdf"

mv_one "opěrný-rám-sb-prospekt.pdf"      "B5_tech_cards/peri_sb_brace_frame/source_prospekt.pdf"

mv_one "peri-cb-240-a-cb-160-prospekt.pdf" \
       "B5_tech_cards/peri_cb_240_cb_160_climbing_formwork/source_prospekt.pdf"

mv_one "prokit-ep-110-návod.pdf"    "B5_tech_cards/peri_prokit_ep_110/source_navod.pdf"
mv_one "prokit-ep-110-prospekt.pdf" "B5_tech_cards/peri_prokit_ep_110/source_prospekt.pdf"

mv_one "quattro-návod.pdf"      "B5_tech_cards/peri_quattro_column_formwork/source_navod.pdf"
mv_one "quattro-prospekt.pdf"   "B5_tech_cards/peri_quattro_column_formwork/source_prospekt.pdf"

mv_one "rcs-lite-návod.pdf"     "B5_tech_cards/peri_rcs_lite_climbing/source_navod.pdf"

mv_one "rundflex-návod.pdf"     "B5_tech_cards/peri_rundflex_circular_wall_formwork/source_navod.pdf"
mv_one "rundflex-prospekt.pdf"  "B5_tech_cards/peri_rundflex_circular_wall_formwork/source_prospekt.pdf"

mv_one "scs-návod.pdf"          "B5_tech_cards/peri_scs_climbing/source_navod.pdf"

mv_one "sky-kotva-návod.pdf"    "B5_tech_cards/peri_sky_anchor/source_navod.pdf"

mv_one "skydeck-návod.pdf"      "B5_tech_cards/peri_skydeck_slab_formwork/source_navod.pdf"
mv_one "skydeck-prospekt.pdf"   "B5_tech_cards/peri_skydeck_slab_formwork/source_prospekt.pdf"

mv_one "srs-návod.pdf"          "B5_tech_cards/peri_srs_climbing/source_navod.pdf"
mv_one "srs-prospekt.pdf"       "B5_tech_cards/peri_srs_climbing/source_prospekt.pdf"

mv_one "stabilizátory-prospekt.pdf"    "B5_tech_cards/peri_stabilizers/source_prospekt.pdf"

mv_one "technika-spínání-dk-sk-návod.pdf"    \
       "B5_tech_cards/peri_dk_sk_tie_system/source_navod.pdf"
mv_one "technika-spínání-dk-sk-prospekt.pdf" \
       "B5_tech_cards/peri_dk_sk_tie_system/source_prospekt.pdf"

mv_one "trio-návod.pdf"         "B5_tech_cards/peri_trio_wall_formwork/source_navod.pdf"
mv_one "trio-prospekt.pdf"      "B5_tech_cards/peri_trio_wall_formwork/source_prospekt.pdf"
mv_one "trio-plakát.pdf"        "B5_tech_cards/peri_trio_wall_formwork/source_plakat.pdf"

mv_one "trs-návod.pdf"          "B5_tech_cards/peri_trs_climbing/source_navod.pdf"

mv_one "vario-návod.pdf"        "B5_tech_cards/peri_vario_wall_formwork/source_navod.pdf"
mv_one "vario-prospekt.pdf"     "B5_tech_cards/peri_vario_wall_formwork/source_prospekt.pdf"

mv_one "variokit-prospekt.pdf"  "B5_tech_cards/peri_variokit_engineering_kit/source_prospekt.pdf"
mv_one "variokit-vgb-návod.pdf" "B5_tech_cards/peri_variokit_vgb/source_navod.pdf"
mv_one "variokit-vst-návod.pdf" "B5_tech_cards/peri_variokit_vst/source_navod.pdf"

# Note: original filename has a typo (variokoit). Slug uses corrected variokit.
mv_one "variokoit-vgk-návod.pdf" "B5_tech_cards/peri_variokit_vgk/source_navod.pdf"

mv_one "výrobní-program-bednění.pdf" \
       "B5_tech_cards/peri_vyrobni_program_bedneni/source.pdf"

mv_one "zásobovací-plošina-rcs-mp-návod.pdf" \
       "B5_tech_cards/peri_rcs_mp_loading_platform/source_navod.pdf"

# B5_tech_cards — Other (4)
mv_one "3F_Technicka_zprava_-_priloha_II.pdf" \
       "B5_tech_cards/general_3f_tp_tabor_rd/source.pdf"
mv_one "Technolog_predpis_BBA-MONOLIT.pdf" \
       "B5_tech_cards/walls_monolithic_cz_bba_monolit_tp01/source.pdf"
mv_one "Příručka pracovníka s betonem.pdf" \
       "B5_tech_cards/general_prirucka_pracovnika_s_betonem/source.pdf"
mv_one "cw15-lad-bedn.pdf" \
       "B5_tech_cards/general_bedneni_zaklady_cw15_lad/source.pdf"

# B6_research_papers (12)
mv_one "032023-betonweb-lock.pdf" \
       "B6_research_papers/journals/beton_2023_03_betonweb/source.pdf"
mv_one "2008.1476868530_MOSTY_A_TUNELY.pdf" \
       "B6_research_papers/conferences/zelezni_mosty_a_tunely_2008/source.pdf"
mv_one "2023-01-beton-web-opravene-lck.pdf" \
       "B6_research_papers/journals/beton_2023_01/source.pdf"
mv_one "BL001_vyukove_texty.pdf" \
       "B6_research_papers/vut_brno_bl001_prvky_betonovych_konstrukci/source.pdf"
mv_one "Betonove_mosty_2.pdf" \
       "B6_research_papers/upa_pokorny_suchanek_betonove_mosty_ii/source.pdf"
mv_one "F1-DP-2020-Belohradska-Lucie-priloha-Vykres_3-Tvar_1PP.pdf" \
       "B6_research_papers/diplomky/unknown_belohradska_2020_vykres_tvar_1pp/source.pdf"
mv_one "HP2011-01-Vaskova.pdf" \
       "B6_research_papers/papers/hp2011_vaskova/source.pdf"
mv_one "MOŽNOSTI SANACE BETONOVÝCH KONSTRUKCÍ.pdf" \
       "B6_research_papers/sanace/moznosti_sanace_betonovych_konstrukci/source.pdf"
mv_one "MZA10- PILOTY.pdf" \
       "B6_research_papers/piloty/mza10_piloty/source.pdf"
mv_one "POROVNÁNÍ ZKUŠEBNÍCH METOD PRO.pdf" \
       "B6_research_papers/papers/porovnani_zkusebnich_metod/source.pdf"
mv_one "PROJEKT DÁLNIČNÍHO NADJEZDU Č. Dl -150.pdf" \
       "B6_research_papers/diplomky/vut_novakova_2019_dalnicni_nadjezd_d1_150/source.pdf"
mv_one "Příručka technologa.pdf" \
       "B6_research_papers/prirucka_technologa_2005/source.pdf"

# B7_regulations (1)
mv_one "Průvodce normou ČSN EN 206+A2.pdf" \
       "B7_regulations/csn_en_206_pruvodce/source.pdf"

# ---------------------------------------------------------------------------
# Phase D — duplicate archive
# ---------------------------------------------------------------------------
gate "PHASE D — archive duplicate (46324_Archive.pdf)"

# 46324_Archive.pdf is identical to PROJEKT DÁLNIČNÍHO NADJEZDU... (already moved
# to B6/diplomky/vut_novakova_2019_dalnicni_nadjezd_d1_150/source.pdf in Phase C).
# We move (not delete) so object versioning preserves the history.
echo "→ 46324_Archive.pdf"
echo "  _archive/duplicates/46324_Archive.pdf"
gsutil mv "${BUCKET}/46324_Archive.pdf" "${ARCHIVE_BUCKET}/46324_Archive.pdf" \
  || { echo "  ✗ archive failed"; exit 1; }

# ---------------------------------------------------------------------------
# Phase E — upload INDEX.json
# ---------------------------------------------------------------------------
gate "PHASE E — upload INDEX.json"

if [ ! -f "${INDEX_FILE}" ]; then
  echo "ERROR: ${INDEX_FILE} missing. Re-run from a clean checkout." >&2
  exit 1
fi
gsutil cp "${INDEX_FILE}" "${INDEX_PATH}" \
  || { echo "  ✗ upload failed"; exit 1; }
echo "  ✓ INDEX.json uploaded to ${INDEX_PATH}"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo
echo "═══════════════════════════════════════════════════════════════════"
echo "  ALL PHASES COMPLETE"
echo "═══════════════════════════════════════════════════════════════════"
echo "  Next step: in Vertex AI console, open Data Store"
echo "  'urs-otskp-csn-norms-cenik' and trigger Manual Sync."
echo "═══════════════════════════════════════════════════════════════════"
