-- URS Matcher Service Database Schema

-- URS Items Catalog
CREATE TABLE IF NOT EXISTS urs_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  urs_code TEXT UNIQUE NOT NULL,
  urs_name TEXT NOT NULL,
  unit TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Jobs (uploaded files or text matches)
CREATE TABLE IF NOT EXISTS jobs (
  id TEXT PRIMARY KEY,
  filename TEXT NOT NULL,
  status TEXT DEFAULT 'processing', -- processing, completed, error
  total_rows INTEGER,
  processed_rows INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Job Items (results for each row in job)
CREATE TABLE IF NOT EXISTS job_items (
  id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL,
  input_row_id INTEGER,
  input_text TEXT NOT NULL,
  urs_code TEXT NOT NULL,
  urs_name TEXT NOT NULL,
  unit TEXT,
  quantity REAL,
  confidence REAL DEFAULT 0.5,
  source TEXT, -- local_match, llm_match, perplexity_search, tech_rule
  explanation TEXT, -- Explanation for why this item was chosen (from LLM or default)
  extra_generated INTEGER DEFAULT 0, -- 1 if auto-generated by tech rules
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (job_id) REFERENCES jobs(id)
);

-- Mapping Examples (for future ML training)
CREATE TABLE IF NOT EXISTS mapping_examples (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  input_text TEXT NOT NULL,
  urs_code TEXT NOT NULL,
  confidence REAL,
  validated_by_user INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_jobs_created ON jobs(created_at);
CREATE INDEX IF NOT EXISTS idx_job_items_job_id ON job_items(job_id);
CREATE INDEX IF NOT EXISTS idx_urs_items_code ON urs_items(urs_code);
CREATE INDEX IF NOT EXISTS idx_urs_items_name ON urs_items(urs_name);
