-- URS Matcher Service Database Schema

-- ============================================================================
-- URS Items Catalog (Full)
-- Purpose: Complete ÚRS code catalog (normally imported from official source)
-- ============================================================================
CREATE TABLE IF NOT EXISTS urs_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  urs_code TEXT UNIQUE NOT NULL,              -- e.g. '3112389'
  urs_name TEXT NOT NULL,                     -- e.g. 'Základové pasy z betonu C25/30'
  unit TEXT NOT NULL,                         -- MJ: m, m2, m3, ks, t, etc.
  description TEXT,                           -- Longer description if available
  section_code TEXT,                          -- Třídník prefix, e.g. '31', '32', '27'
  category_path TEXT,                         -- Hierarchy path, e.g. '3 > 31 > Zdivo'
  is_imported INTEGER DEFAULT 0,              -- 1 = from official catalog, 0 = sample/manual
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for fast lookup and filtering by section
CREATE INDEX IF NOT EXISTS idx_urs_code ON urs_items(urs_code);
CREATE INDEX IF NOT EXISTS idx_urs_name ON urs_items(urs_name);
CREATE INDEX IF NOT EXISTS idx_urs_section_code ON urs_items(section_code);
CREATE INDEX IF NOT EXISTS idx_urs_is_imported ON urs_items(is_imported);

-- Jobs (uploaded files or text matches)
CREATE TABLE IF NOT EXISTS jobs (
  id TEXT PRIMARY KEY,
  filename TEXT NOT NULL,
  status TEXT DEFAULT 'processing', -- processing, completed, error
  total_rows INTEGER,
  processed_rows INTEGER,
  project_context TEXT, -- JSON: building_type, storeys, main_system, notes
  results_json TEXT, -- JSON: Complete block-match results for Excel export
  -- ⭐ UNIFIED: Link to Portal project (for cross-service data sharing)
  portal_project_id TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Job Items (results for each row in job)
CREATE TABLE IF NOT EXISTS job_items (
  id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL,
  input_row_id INTEGER,
  input_text TEXT NOT NULL,
  urs_code TEXT NOT NULL,
  urs_name TEXT NOT NULL,
  unit TEXT,
  quantity REAL,
  confidence REAL DEFAULT 0.5,
  source TEXT, -- local_match, llm_match, perplexity_search, tech_rule
  explanation TEXT, -- Explanation for why this item was chosen (from LLM or default)
  extra_generated INTEGER DEFAULT 0, -- 1 if auto-generated by tech rules
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (job_id) REFERENCES jobs(id)
);

-- Mapping Examples (for future ML training)
CREATE TABLE IF NOT EXISTS mapping_examples (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  input_text TEXT NOT NULL,
  urs_code TEXT NOT NULL,
  confidence REAL,
  validated_by_user INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- Knowledge Base: Store confirmed mappings for fast reuse (NEW)
-- ============================================================================
-- Purpose: Cache confirmed text-to-URS mappings to avoid redundant LLM calls
-- and accelerate matching for recurring constructions patterns
-- ============================================================================
CREATE TABLE IF NOT EXISTS kb_mappings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,

  -- Normalized input (Czech technical description)
  normalized_text_cs TEXT NOT NULL,           -- e.g. "betonova deska prehlazena"
  language_hint TEXT DEFAULT 'cs',            -- original language: cs, ru, uk, en, de, other

  -- Context (for semantic grouping)
  context_hash TEXT,                          -- hash(project_type + building_system)
  project_type TEXT,                          -- e.g. "bytový dům", "rodinný dům", "průmyslová hala"
  building_system TEXT,                       -- e.g. "monolitický ŽB", "zděné"

  -- Matched URS (must exist in urs_items)
  urs_code TEXT NOT NULL,
  urs_name TEXT NOT NULL,
  unit TEXT NOT NULL,

  -- Confidence and usage tracking
  confidence REAL DEFAULT 0.8,                -- how confident in this mapping (0-1)
  usage_count INTEGER DEFAULT 1,              -- how many times this mapping was used/confirmed
  last_used_at TIMESTAMP,

  -- Data quality
  validated_by_user INTEGER DEFAULT 0,        -- 1 if manually approved, 0 if auto-learned
  validation_comment TEXT,

  -- Metadata
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  -- Unique constraint: same normalized text + context = one mapping
  UNIQUE(normalized_text_cs, context_hash)
);

-- Suggested Related Items (complementary works from knowledge base)
CREATE TABLE IF NOT EXISTS kb_related_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,

  -- Reference to primary KB mapping
  kb_mapping_id INTEGER NOT NULL,

  -- Related URS item
  urs_code TEXT NOT NULL,
  urs_name TEXT NOT NULL,
  unit TEXT NOT NULL,

  -- Why is this related?
  reason_cs TEXT,                             -- Czech explanation
  relationship_type TEXT,                     -- "complementary", "prerequisite", "sequential"
  typical_sequence_order INTEGER,             -- 1=first, 2=second, etc.

  -- Confidence
  co_occurrence_count INTEGER DEFAULT 1,      -- how many times seen together

  FOREIGN KEY (kb_mapping_id) REFERENCES kb_mappings(id),
  UNIQUE(kb_mapping_id, urs_code)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_jobs_created ON jobs(created_at);
CREATE INDEX IF NOT EXISTS idx_jobs_portal_project ON jobs(portal_project_id);
CREATE INDEX IF NOT EXISTS idx_job_items_job_id ON job_items(job_id);

-- Knowledge Base indexes
CREATE INDEX IF NOT EXISTS idx_kb_normalized_text ON kb_mappings(normalized_text_cs);
CREATE INDEX IF NOT EXISTS idx_kb_context_hash ON kb_mappings(context_hash);
CREATE INDEX IF NOT EXISTS idx_kb_urs_code ON kb_mappings(urs_code);
CREATE INDEX IF NOT EXISTS idx_kb_usage ON kb_mappings(usage_count DESC);
CREATE INDEX IF NOT EXISTS idx_kb_confidence ON kb_mappings(confidence DESC);
CREATE INDEX IF NOT EXISTS idx_kb_related_items ON kb_related_items(kb_mapping_id);

-- ============================================================================
-- CATALOG VERSIONING & MANAGEMENT (NEW)
-- ============================================================================
-- Track all catalog imports with versions, status, validation, and rollback capability
-- ============================================================================

CREATE TABLE IF NOT EXISTS catalog_versions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  version_id TEXT UNIQUE NOT NULL,       -- e.g. 'catalog_1702200000000'
  source TEXT NOT NULL,                  -- 'local_file', 's3_bucket', 'api_endpoint', etc.
  source_info TEXT,                      -- JSON with source details (file path, URL, etc.)

  -- Status workflow
  status TEXT DEFAULT 'pending',         -- pending, approved, active, inactive, rejected, archived
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  approved_at TIMESTAMP,
  approved_by TEXT,                      -- User who approved
  approval_notes TEXT,                   -- Why approved/rejected
  activated_at TIMESTAMP,                -- When version became active
  rejection_reason TEXT,

  -- Import statistics
  stats TEXT,                            -- JSON: {total, skipped, duplicates, bySection, ...}
  validation_score INTEGER,              -- 0-100 quality score
  validation_details TEXT,               -- JSON: {valid, errors, warnings, ...}

  -- Metadata
  imported_codes_count INTEGER,          -- Total codes imported
  section_coverage TEXT,                 -- JSON: {"27": 1200, "31": 850, ...}
  archive_path TEXT,                     -- Path to archived copy if archived

  UNIQUE(version_id)
);

-- Audit log for all catalog operations
CREATE TABLE IF NOT EXISTS catalog_audit_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  action TEXT NOT NULL,                  -- import_started, import_completed, version_approved, etc.
  details TEXT,                          -- JSON with detailed info
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id TEXT,                          -- Who triggered the action
  ip_address TEXT                        -- For security audit
);

-- Index for efficient queries
CREATE INDEX IF NOT EXISTS idx_catalog_versions_status ON catalog_versions(status);
CREATE INDEX IF NOT EXISTS idx_catalog_versions_created ON catalog_versions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_catalog_versions_active ON catalog_versions(status) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_catalog_audit_action ON catalog_audit_log(action);
CREATE INDEX IF NOT EXISTS idx_catalog_audit_timestamp ON catalog_audit_log(timestamp DESC);

