'use client';

import React from 'react';
import { ReportArtifact } from '@/lib/artifact-types';

interface ReportArtifactViewProps {
  artifact: ReportArtifact;
  editMode: boolean;
  onUpdate: (artifact: any) => void;
}

export function ReportArtifactView({ artifact, editMode, onUpdate }: ReportArtifactViewProps) {
  // Mock data if not provided
  const sections = artifact.sections || [
    {
      id: 'intro',
      title: 'Introduction',
      content: 'This report summarizes the technical analysis of the concrete foundation project.',
      order: 1,
      type: 'text' as const,
    },
    {
      id: 'findings',
      title: 'Key Findings',
      content:
        '- Total concrete volume required: 42 m³\n- Reinforcement steel: 3,200 kg\n- Estimated project cost: 230,100 CZK',
      order: 2,
      type: 'text' as const,
    },
    {
      id: 'recommendations',
      title: 'Recommendations',
      content:
        '1. Use concrete class C30/37 for adequate strength\n2. Apply waterproofing for XD2 exposure\n3. Follow ČSN 73 1201 standards',
      order: 3,
      type: 'text' as const,
    },
  ];

  const metadata = artifact.metadata || {
    author: 'Multi-Role AI Assistant',
    projectName: 'Foundation Project',
    date: new Date(),
    version: '1.0',
    tags: ['concrete', 'foundation', 'technical'],
  };

  return (
    <div className="space-y-6">
      {/* Report Header */}
      <div className="bg-white border border-gray-200 rounded-lg p-6">
        <h1 className="text-2xl font-bold text-gray-900 mb-2">{artifact.title}</h1>
        <div className="grid grid-cols-2 gap-4 text-sm text-gray-600 mt-4">
          <div>
            <span className="font-medium">Project:</span> {metadata.projectName}
          </div>
          <div>
            <span className="font-medium">Date:</span> {metadata.date.toLocaleDateString()}
          </div>
          <div>
            <span className="font-medium">Author:</span> {metadata.author}
          </div>
          <div>
            <span className="font-medium">Version:</span> {metadata.version}
          </div>
        </div>
        {metadata.tags && (
          <div className="mt-4 flex gap-2">
            {metadata.tags.map((tag) => (
              <span
                key={tag}
                className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-700"
              >
                {tag}
              </span>
            ))}
          </div>
        )}
      </div>

      {/* Report Sections */}
      {sections.map((section) => (
        <div key={section.id} className="bg-white border border-gray-200 rounded-lg p-6">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">{section.title}</h2>
          <div className="prose prose-sm max-w-none">
            <p className="text-gray-700 whitespace-pre-wrap">{section.content}</p>
          </div>
        </div>
      ))}

      {/* Report Footer */}
      <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 text-center text-xs text-gray-500">
        Generated by Concrete Agent Multi-Role AI System • {new Date().toLocaleString()}
      </div>
    </div>
  );
}
